import { Colors, Fonts, ScaleHeight, ScaleWidth } from "common";
import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
    justifyContent: "flex-start",
  },
  sectorBox: {
    marginEnd: ScaleWidth(10),
    padding: ScaleWidth(5),
    borderRadius: ScaleWidth(5),
  },
  sectorTxt: {
    fontSize: ScaleWidth(16),
    fontWeight: "400",
  },
  brandBox: {
    marginEnd: ScaleWidth(10),
    borderWidth: ScaleWidth(1),
    padding: ScaleWidth(5),
    borderColor: Colors.gray3,
    borderRadius: ScaleWidth(5),
  },
  brandTxt: {
    fontSize: ScaleWidth(16),
    color: Colors.red,
    fontWeight: "500",
    textTransform: "uppercase",
  },
  serviceBox: {
    width: ScaleWidth("42%"),
    height: ScaleHeight("10%"),
    alignItems: "center",
    justifyContent: "center",
    padding: ScaleWidth(5),
    borderRadius: ScaleWidth(5),
    backgroundColor: Colors.scondary,
    marginVertical: ScaleHeight(5),
  },
  serviceTxt: {
    fontSize: ScaleWidth(16),
    fontWeight: "600",
    color: Colors.white,
  },
  rowWrap: {
    paddingHorizontal: ScaleWidth(20),
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
  },
  offersBox: {
    width: ScaleWidth("43%"),
    height: ScaleHeight("30%"),
    alignItems: "center",
    justifyContent: "flex-start",
    padding: ScaleWidth(5),
    borderRadius: ScaleWidth(5),
    backgroundColor: Colors.white,
    borderWidth: ScaleWidth(1),
    borderColor: Colors.gray2,
    marginVertical: ScaleHeight(5),
  },
  offerImgBox: {
    width: ScaleWidth("30%"),
    height: ScaleHeight("10%"),
  },
  likeBox: {
    position: "absolute",
    width: ScaleWidth(30),
    height: ScaleWidth(30),
    borderRadius: ScaleWidth(15),
    right: 5,
    top: 10,
    backgroundColor: Colors.gray3,
    zIndex: 2,
    alignItems: "center",
    justifyContent: "center",
  },
  offerBottomBox: {
    width: ScaleWidth("43%"),
    height: ScaleHeight("18%"),
    alignItems: "center",
    padding: ScaleWidth(10),
    borderTopLeftRadius: ScaleWidth(20),
    borderTopRightRadius: ScaleWidth(20),
    borderBottomLeftRadius: ScaleWidth(5),
    borderBottomRightRadius: ScaleWidth(5),
    borderWidth: ScaleWidth(1),
    borderColor: Colors.gray2,
    position: "absolute",
    bottom: 0,
  },
  offerTxt: {
    fontSize: ScaleWidth(16),
    color: Colors.primary,
    fontWeight: "500",
    textTransform: "capitalize",
    textAlign: "center",
    paddingBottom: ScaleHeight(5),
  },
});

export default styles;
